name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  tests:
    needs: [build]
    uses: Marod12/desafio-cicd-01/.github/workflows/tests.yml@main
    secrets: inherit

  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
    - name: Obtendo o código do projeto
      uses: actions/checkout@v4

    - name: Analise do Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./src/Review-Filmes.Web/Dockerfile

    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Review-Filmes.Web/Dockerfile
        push: true
        tags: | 
          marod12/pipeline-0-master:v${{ github.run_number }} 
          marod12/pipeline-0-master:latest

    - name: Scan co trivy
      uses: aquasecurity/trivy-action@0.23.0
      with:
        scan-type: 'image'
        image-ref: 'marod12/pipeline-0-master:v${{ github.run_number }}'
        format: 'sarif'
        output: trivy-docker-result.sarif
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

    - name: Upload do arquivo trivy para o github
      uses: github/codeql-action/upload-safif@v1
      with:
        category: docker-result
        sarif_file: trivy-docker-result.sarif
